runtime: python27
api_version: '1'
env: standard
threadsafe: true

handlers:
  - url: '/.*'
    script: main.app

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic